[package]
name = 'controller_remap'
version = '0.1.0'
edition = '2021'

[dependencies]
duration-str = '*'
enigo = { version = '0.2.0-rc2', default-features = false, features = ['serde', 'wayland'] }
gilrs = { version = '*', features = ['serde'] }
lazy_static = '*'
serde = '*'
shlex = '*'
single-instance = '*'
tokio = { version = '*', features = ['macros', 'rt-multi-thread', 'time'] }
toml = '*'

[target.'cfg(target_os = "linux")'.dependencies]
nix = { version = '*', default-features = false, features = ['signal'] }

[patch.crates-io]
enigo = { git = 'https://github.com/enigo-rs/enigo.git' }
