[package]
name = 'controller_remap'
version = '0.1.0'
edition = '2021'

[dependencies]
enigo = { version = '0.2.0-rc2', default-features = false, features = ['serde', 'wayland'] }
gilrs = { version = '*', features = ['serde'] }
lazy_static = '*'
serde = '*'
shlex = '*'
tokio = { version = '*', features = ['macros', 'process', 'rt-multi-thread', 'sync', 'time'] }
toml = '*'
