[package]
name = 'controller-remap'
description = 'Remap controller to keyboard and mouse inputs'
license-file = 'LICENSE'
version = '1.0.0'
edition = '2021'

[dependencies]
duration-str = '*'
enigo = { version = '*', default-features = false, features = ['serde', 'wayland'] }
gilrs = { version = '*', features = ['serde'] }
if_chain = '*'
lazy_static = '*'
serde = '*'
shlex = '*'
single-instance = '*'
tokio = { version = '*', features = ['macros', 'rt-multi-thread', 'time'] }
toml = '*'

[target.'cfg(target_os = "linux")'.dependencies]
nix = { version = '*', default-features = false, features = ['signal'] }
