[package]
name = 'controller_remap'
version = '0.1.0'
edition = '2021'

[dependencies]
sdl2 = '*'
serde = { version = '*', features = ['derive'] }
toml = '*'

[target.'cfg(target_os = "windows")'.dependencies]
windows-sys = { version = '*', features = ['Win32_UI_Input_KeyboardAndMouse'] }

[target.'cfg(target_os = "linux")'.dependencies]
uinput = '*'
