name: CI

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        platform: [windows-latest, ubuntu-latest]
      fail-fast: false

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system-specific dependencies
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libudev-dev libxkbcommon-dev

      - name: Build
        run: cargo build --release

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.configuration }} ${{ matrix.platform }}
          path: |
            target/release/controller-remap.exe
            target/release/controller-remap
          if-no-files-found: error
